name: tests

on:
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
      - "**:**"

jobs:
  golangci-lint:
    name: Golang-CI (lint)
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run linter
        uses: golangci/golangci-lint-action@v2 # Action page: <https://github.com/golangci/golangci-lint-action>
        with:
          version: v1.38 # without patch version
          only-new-issues: false # show only new issues if it's a pull request

  go-test:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fixes codecov error 'Issue detecting commit SHA'

      - name: Init Go modules Cache # Docs: <https://git.io/JfAKn#go---modules>
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: go mod download && go mod verify

      - name: Run Unit tests
        run: go test -race -covermode=atomic -coverprofile /tmp/coverage.txt ./...

      - name: Upload Coverage report to CodeCov
        continue-on-error: true
        uses: codecov/codecov-action@v1 # https://github.com/codecov/codecov-action
        with:
          file: /tmp/coverage.txt

  build:
    name: Build (Go ${{ matrix.go }}, OS ${{matrix.os}})
    runs-on: ${{ matrix.os }}
    needs: [ golangci-lint, go-test ]
    strategy:
      fail-fast: false
      matrix:
        go: [ "1.15", "1.16" ]
        os: [ ubuntu-20.04 ]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Init Go modules Cache # Docs: <https://git.io/JfAKn#go---modules>
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: go mod download && go mod verify

      - name: Build
        run: go build -o ./rr ./cmd/rr

      - name: Try to execute
        run: ./rr -v && ./rr -h

  docker-image:
    name: Build docker image
    runs-on: ubuntu-20.04
    needs: [ golangci-lint, go-test ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t rr:local -f ./Dockerfile .

      - name: Try to execute
        run: docker run --rm rr:local -v

      - name: Scan image
        uses: anchore/scan-action@v2 # action page: <https://github.com/anchore/scan-action>
        with:
          image: rr:local
          fail-build: true
          severity-cutoff: low # negligible, low, medium, high or critical
